version: '3.8'

services:
  apache:
    build: './docker/apache/'
    ports:
      - '8000:80'
      - '8443:443'
    volumes:
      - ./:/var/www/html/

  mysql:
    image: mysql:5.7.39
    ports:
      - '8306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root

  php:
    build: './docker/php/'
    volumes:
      - ./:/var/www/html
