version: '3.8'

services:
  apache:
    build: './docker/apache/'
    ports:
      - '8000:80'
      - '8443:443'
    volumes:
      - ./:/var/www/html/

  mysql:
    image: mysql:5.7.39
    ports:
      - '8306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./container-files/mysql:/var/lib/mysql

  php:
    build: './docker/php/'
    volumes:
      - ./:/var/www/html
