openapi: 3.0.0
info:
  title: 'GeekLab MyExporter API'
  version: '0.1'
paths:
  /login:
    post:
      tags:
        - auth
      summary: 'Login with server index, username and password'
      description: 'Perform login.'
      operationId: authLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - host
                - username
                - password
              properties:
                host:
                  type: integer
                username:
                  type: string
                password:
                  type: string
              type: object
      responses:
        '200':
          description: 'JWT Response'
          content:
            application/json:
              schema:
                properties:
                  message: { type: string, example: success }
                  jwt: { type: string }
                type: object
        '401':
          description: Unauthorized
  /databases:
    get:
      summary: 'Require authentication'
      operationId: d9efa44c5ef7e1555747d07ff6a07edd
      responses:
        '200':
          description: 'Get a list of List of databases from a server, filter by excluded'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { database: { description: 'The database name', type: string, example: DB1 } }
                  type: object
  '/databases/{database}/tables':
    get:
      summary: 'Require authentication'
      description: 'Return a list of tables in a database.'
      operationId: 4e41018aeda131108ce22958e475aa20
      responses:
        '200':
          description: 'List of tables'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { table: { description: 'The table name', type: string, example: myTable }, size: { description: 'The table size in bytes', type: integer, example: '102452' } }
                  type: object
  /servers:
    get:
      summary: 'Return array of indexed server names. No authentication needed.'
      operationId: e0530026be94cb78d3a4a2b5514def40
      responses:
        '200':
          description: 'List of servers'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { id: { type: integer, example: '0' }, name: { type: string, example: 'The DB Server Name' } }
                  type: object
components:
  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      in: header
      bearerFormat: JWT
      scheme: bearer
